#!/system/bin/sh
#
# Print startup info
#
L="log -p i -t intense"

$L "  _____       _                          ___  __  ";
$L "  \_   \_ __ | |_ ___ _ __  ___  ___    /___\/ _\ ";
$L "   / /\/ '_ \| __/ _ \ '_ \/ __|/ _ \  //  //\ \  ";
$L "/\/ /_ | | | | ||  __/ | | \__ \  __/ / \_// _\ \ ";
$L "\____/ |_| |_|\__\___|_| |_|___/\___| \___/  \__/ ";
$L "Welcome to Android `getprop ro.build.version.release` / IntenseOS-`getprop ro.intense.version`";
